### ISSUE TITLE
Quitting an FX2D app (via ESC or cmd-Q) on macOS throws IllegalStateException

### ISSUE THREAD

**Issue by benfry** [processing/processing4-javafx#4]
Using ESC to quit an app results in
```
java.lang.IllegalStateException: Not on FX application thread; currentThread = JavaFX Application Thread
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.stage.Window.setShowing(Window.java:921)
	at javafx.stage.Window.hide(Window.java:947)
	at com.sun.javafx.stage.WindowPeerListener.closed(WindowPeerListener.java:100)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:119)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$423(GlassWindowEventHandler.java:151)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:149)
	at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1266)
	at com.sun.glass.ui.Window.notifyDestroy(Window.java:1183)
```

**Comment by hkiel** [comment]
I seem to have fixed that issue on macOS (#5574). Cannot check other architectures, though...

**Comment by benfry** [comment]
Still need help with a fix for this one… Stack trace from the beta 4 release:

```
java.lang.IllegalStateException: Not on FX application thread; currentThread = JavaFX Application Thread
	at javafx.graphics/com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:295)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:458)
	at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1189)
	at javafx.graphics/javafx.stage.Window.hide(Window.java:1215)
	at javafx.graphics/com.sun.javafx.stage.WindowPeerListener.closed(WindowPeerListener.java:105)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:144)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:178)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:176)
	at javafx.graphics/com.sun.glass.ui.Window.handleWindowEvent(Window.java:1336)
	at javafx.graphics/com.sun.glass.ui.Window.notifyDestroy(Window.java:1250)
IllegalStateException: Not on FX application thread; currentThread = JavaFX Application Thread
```
